[package]
name = "rust_raytrace"
version = "0.1.0"
edition = "2024"

[dependencies]
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
rand = { version = "0.8", features = ["small_rng"] }
rayon = "1.10"
